- name: cndl statement
  hosts: local
  connection: local
  vars_prompt:
  - name: your_no
    prompt: enter a number
    private: false
  tasks:
  - name: print if less than 10
    ansible.builtin.debug:
      msg: "given number {{your_no}}vis less than 10"
    when: your_no | int < 10
  - name: print if greater than 10
    ansible.builtin.debug:
      msg: "given number {{your_no}}vis greater than 10"
    when: your_no | int >= 10
