- name: 
  hosts: ANS
  become: yes
  tasks:
  - name: create loop
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - { name: 'mysql',state: 'present' }
    - { name: 'nginx',state: 'present' }
    - { name: 'server',state: 'present' }
 